CREATE DATABASE GESTION_ALUMNOS;

USE GESTION_ALUMNOS;

CREATE TABLE ESTADO
(
	ID_ESTADO INT PRIMARY KEY IDENTITY(1,1),
	DESC_ESTADO NVARCHAR(50) NOT NULL,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE()
);
INSERT INTO ESTADO(DESC_ESTADO) VALUES ('ACTIVO');

CREATE TABLE CARRERA
(
    ID_CARRERA NVARCHAR(10) PRIMARY KEY,
	DESC_CARRERA NVARCHAR (150) NOT NULL,
	CREDITOS INT NOT NULL,
	CREDITOS_COM INT NOT NULL,
	ID_ESTADO INT NOT NULL DEFAULT 1,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE(),
	FH_MOD DATETIME2 NULL,
	CONSTRAINT FK_CARRERA_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);
INSERT INTO CARRERA(ID_CARRERA,DESC_CARRERA,CREDITOS,CREDITOS_COM) VALUES ('ING-INF-01','INGENIERÍA INFORMÁTICA',255,5);

CREATE TABLE PROFESOR
(
	ID_PROFE NVARCHAR(8) PRIMARY KEY,
	NOMBRE_P NVARCHAR (150) NOT NULL,
	PRIMER_AP NVARCHAR (100) NOT NULL,
	SEGUNDO_AP NVARCHAR (100) NULL,
	ID_CARRERA NVARCHAR(10) NULL,
	ES_TUTOR INT DEFAULT 0,
	ID_ESTADO INT NOT NULL DEFAULT 1,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE(),
	FH_MOD DATETIME2 NULL,
	CONSTRAINT FK_PROFESOR_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
	CONSTRAINT FK_PROFESOR_CARRERA FOREIGN KEY(ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
);
INSERT INTO PROFESOR(ID_PROFE,NOMBRE_P,PRIMER_AP,SEGUNDO_AP,ID_CARRERA,ES_TUTOR) VALUES ('21PF0220','JUAN','FLORES','FLORES','ING-INF-01',1);

CREATE TABLE ALUMNO
(
	NO_CONTROL NVARCHAR(8) PRIMARY KEY,
	NOMBRE_A NVARCHAR (150) NOT NULL,
	PRIMER_AP NVARCHAR (100) NOT NULL,
	SEGUNDO_AP NVARCHAR (100) NULL,
	ID_CARRERA NVARCHAR(10) NOT NULL,
	SEMESTRE INT DEFAULT 1,
	ID_TUTOR NVARCHAR(8) NOT NULL,
	ID_ESTADO INT NOT NULL DEFAULT 1,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE(),
	FH_MOD DATETIME2 NULL,
	CONSTRAINT FK_ALUMNO_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
	CONSTRAINT FK_ALUMNO_TUTOR FOREIGN KEY(ID_TUTOR) REFERENCES PROFESOR(ID_PROFE),
	CONSTRAINT FK_ALUMNO_CARRERA FOREIGN KEY(ID_CARRERA) REFERENCES CARRERA(ID_CARRERA)
);
INSERT INTO ALUMNO(NO_CONTROL,NOMBRE_A,PRIMER_AP,SEGUNDO_AP,ID_CARRERA,ID_TUTOR) VALUES ('21AL0220','JOSE FRANCISCO','CHAVEZ','FLORES','ING-INF-01','21PF0220');

CREATE TABLE ACT_EXTRACURRUCULAR
(
	ID_ACT NVARCHAR(8) PRIMARY KEY,
	DES_ACTIVIDAD NVARCHAR(255) NOT NULL,
	CREDITOS INT NOT NULL DEFAULT 1,
	ID_ESTADO INT NOT NULL DEFAULT 1,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_ACT_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);
INSERT INTO ACT_EXTRACURRUCULAR(ID_ACT,DES_ACTIVIDAD,CREDITOS) VALUES ('ACT-2022','ESCULTURA CON MATERIAL RECICLABLE',2);

CREATE TABLE MATERIA
(
	ID_MATERIA NVARCHAR(8) PRIMARY KEY,
	DESC_MATERIA NVARCHAR(255) NOT NULL,
	ID_ESTADO INT NOT NULL DEFAULT 1,
	CREDITOS INT NOT NULL,
	SEMESTRE INT NOT NULL,
	POS_1 INT NOT NULL DEFAULT 0,
	POS_2 INT NOT NULL DEFAULT 0,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE(),
	FH_MOD DATETIME2 NULL,
	CONSTRAINT FK_MATERIA_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);
INSERT INTO MATERIA(ID_MATERIA,DESC_MATERIA,CREDITOS,SEMESTRE,POS_1,POS_2) VALUES ('MAT-2022','TALLER DE ETICA',4,1,1,1);

CREATE TABLE PERIODO
(
	ID_PERIODO INT PRIMARY KEY IDENTITY(1,1),
	DES_PERIODO NVARCHAR(250) NOT NULL,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE()
);
INSERT INTO PERIODO(DES_PERIODO) VALUES ('AGOSTO-DICIEMBRE');

CREATE TABLE MATERIA_DISPONIBLE
(
	ID_HORARIO NVARCHAR(8) PRIMARY KEY,
	ID_MATERIA NVARCHAR(8) NULL,
	ID_ACT NVARCHAR(8) NULL,
	ID_PROFE  NVARCHAR(8) NOT NULL,
	FH_INI DATE NOT NULL,
	FH_FIN DATE NOT NULL,
	ID_ESTADO INT NOT NULL DEFAULT 1,
	PERIODO INT NOT NULL,
	CUPO INT NOT NULL,
	FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE(),
	FH_MOD DATETIME2 NULL,
	CONSTRAINT FK_MDISPONIBLES_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
	CONSTRAINT FK_MDISPONIBLES_PROFE FOREIGN KEY(ID_PROFE) REFERENCES PROFESOR(ID_PROFE),
	CONSTRAINT FK_MDISPONIBLES_AEXT FOREIGN KEY(ID_ACT) REFERENCES ACT_EXTRACURRUCULAR(ID_ACT),
	CONSTRAINT FK_MDISPONIBLES_PERIODO FOREIGN KEY(PERIODO) REFERENCES PERIODO(ID_PERIODO),
	CONSTRAINT FK_MDISPONIBLES_MATERIA FOREIGN KEY(ID_MATERIA) REFERENCES MATERIA(ID_MATERIA)
);
INSERT INTO MATERIA_DISPONIBLE(ID_HORARIO,ID_MATERIA,ID_PROFE,FH_INI,FH_FIN,CUPO,PERIODO) VALUES ('HOR-0612','MAT-2022','21PF0220','2026-06-12','2026-12-12',15,1);

CREATE TABLE HORARIO_DETALLE
(
    ID INT IDENTITY PRIMARY KEY,
    ID_HORARIO NVARCHAR(8) NOT NULL,
    DIA INT NOT NULL,
    HORA_INI TIME NOT NULL,
    HORA_FIN TIME NOT NULL,
    CONSTRAINT FK_HD_HORARIO FOREIGN KEY(ID_HORARIO) 
        REFERENCES MATERIA_DISPONIBLE(ID_HORARIO)
);

CREATE TABLE INSCRIPCION
(
    CONSE INT PRIMARY KEY IDENTITY(1,1),
    ID_ALUMNO NVARCHAR(8) NOT NULL,
    ID_HORARIO NVARCHAR(8) NOT NULL,
    FH_ALTA DATETIME2 NOT NULL DEFAULT GETDATE(),
    FH_MOD DATETIME2 NULL,
    CONSTRAINT FK_INSCRIPCION_ALUMNO FOREIGN KEY(ID_ALUMNO) REFERENCES ALUMNO(NO_CONTROL),
    CONSTRAINT FK_INSCRIPCION_HORARIO FOREIGN KEY(ID_HORARIO) REFERENCES MATERIA_DISPONIBLE(ID_HORARIO)
);

